### ISSUE TITLE
Honeycomb does not work with single value table

### ISSUE THREAD

**Issue by thistooksomedoing** [dynatrace-oss/DynatraceDashboardPowerups#100]
The honeycomb does not report nor colourise correctly when the underlying table created in data explorer only has a single value, e.g., Session count - estimated active sessions (by users, user type) [web] with no splits. Split this metric by users to get 2 values back, and the honeycomb work fine.

![image](https://user-images.githubusercontent.com/91284658/134564285-09ee2c63-c86f-46b8-ba7e-93fb15d11fdf.png)
![image](https://user-images.githubusercontent.com/91284658/134564416-faddd7a2-566c-46d9-92fd-0ad3bae7d2df.png)
![image](https://user-images.githubusercontent.com/91284658/134564487-aedb825b-f837-4e1e-9b7e-6fb45d9e9f58.png)
![image](https://user-images.githubusercontent.com/91284658/134564794-b32e72af-4f03-4839-8e69-0f7944b126a1.png)

Something to do with the single value table having no heading for the entry?

**Comment by LucasHocker** [comment]
Added error handling for blank first column. Now correctly shows value as value instead of name. Pushed to GitHub, added to ChromeStore 1.56
