### ISSUE TITLE
Honeycomb thresholds cannot accommodate for data explorer SI abbreviations

### ISSUE THREAD

**Issue by thistooksomedoing** [dynatrace-oss/DynatraceDashboardPowerups#101]
![image](https://user-images.githubusercontent.com/91284658/134566322-138bcdf5-03ea-4220-bf8a-495e359c8951.png)
![image](https://user-images.githubusercontent.com/91284658/134566413-0d935a88-755a-4c29-986c-b6cc5b6fa9d2.png)

In this example, the honeycomb sees the 1.7k as 1.7, and therefore a lower number. Setting the warning threshold at 5 colours the tile yellow, when both should be green as they are both higher than 5.

**Comment by LucasHocker** [comment]
Is unit handling necessary here? Setting thresholds in Explorer should not require setting other thresholds in Powerup markup. Your screenshot show correct threshold coloring in explorer, without additional thresholds in Powerup markup, it should simply use the colors from Explorer.

**Comment by thistooksomedoing** [comment]
Ah, I didn't think to check that; I assumed that nay colour coding in explorer would be overridden by the powerup. So, if I omitted thresholds in the powerup, it would just inherit the colours for the cells from explorer then?

I do wonder though, for those scenarios where we don't bother colouring in explorer, the honeycomb is still interpreting 1.7k as 1.7, so it would be seen as being lower than the 796 of the other data row, and that could confuse things.

**Comment by LucasHocker** [comment]
Correct this would still affect thresholds for USQL based Honeycombs. I'd prefer to steer users towards in-product functionality whenever possible. I'm thinking I should disable thresholds if it's an explorer tile and eventually add unit conversion if it's a USQL tile.

**Comment by thistooksomedoing** [comment]
I agree with you there; if there's in-product functionality available, using that would be best. I'll do that for any explorer based tiles then.

**Comment by LucasHocker** [comment]
I've disabled the threshold functionality for Explorer tiles as discussed. Also in trying to build a reproducer case for USQL, it seems USQL only ever gives one unit for a field, e.g. for time it's always `ms` even for larger values. Thus, I feel there's nothing more needed here. Please reopen if you think otherwise. Thanks!
