### ISSUE TITLE
Gauge powerup not working

### ISSUE THREAD

**Issue by thistooksomedoing** [dynatrace-oss/DynatraceDashboardPowerups#102]
We're tried creating a gauge using the powerups following the online documentation. The single value returns, but the powerup does not appear to be reformatting the tile and it stays as is.

![image](https://user-images.githubusercontent.com/91284658/134967895-03076817-07fa-4511-b2de-64bc0f46020d.png)

Title of tile is:
Single value !PU(gauge):stops=.5,.75,.9;colors=green,yellow,orange,red;min=0;max=100

**Comment by LucasHocker** [comment]
Thanks for the hint. Should be an easy fix.

**Comment by LucasHocker** [comment]
Refactored Gauge to support Explorer and USQL SVTs. Pushed to GitHub library, will be included in ChromeStore 1.56.
