### ISSUE TITLE
Unable to specify colourized thresholds to all honeycomb tiles from data explorer

### ISSUE THREAD

**Issue by thistooksomedoing** [dynatrace-oss/DynatraceDashboardPowerups#105]
If you have 2 or more metrics in a data explorer query, you can only specify thresholds to one metric at a time. This results in only the corresponding tiles in the honeycomb being coloured; the others remain greyed out.

![image](https://user-images.githubusercontent.com/91284658/135952465-c1d32b92-68f1-491c-a450-62589058c4c9.png)
![image](https://user-images.githubusercontent.com/91284658/135952789-cee0a73b-83bc-4b1f-98c9-c23c7fe07c53.png)

Would be great if you could apply thresholds to all values returned, rather than toggling between one column or the other. Maybe the coming change where columns can be renamed to being the same is the fix as this also relates to the limitation where the value is shown as zero?

**Comment by LucasHocker** [comment]
Hmm… interesting. I assume the natural follow-on would be separate thresholds per series, eg 1s for load action and 250ms for xhr. From a PowerUps perspective, I would recommend using two source tiles. There’s an option for linked tables. Then each has its own threshold.

I’ll also run this by the Explorer team to see how they might handle in the future.

**Comment by thistooksomedoing** [comment]
Using linked tables almost does the trick with regards colouring the correct, independent thresholds....

....ut, the child (C) values show up as being zero when blended with the parent (P).

![image](https://user-images.githubusercontent.com/91284658/136056008-a7e91f8b-be75-4318-8ddc-b3fd31f38f48.png)
![image](https://user-images.githubusercontent.com/91284658/136056331-aee802f2-e8e7-496e-932a-9dc1a54a586f.png)

**Comment by LucasHocker** [comment]
Linked honeycombs used to require the metric to be the same, thus you would have to use Load + Load. This has been enhanced so you can now use Load + XHR. Pushed to GitHub, ChromeStore 1.57.
