### ISSUE TITLE
Forecast analysis can't plot the entire graph if there are time slices with no data

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#107]
![image](https://user-images.githubusercontent.com/21313331/136575288-9a5b4f7a-5767-41eb-afa7-026e2aa38809.png)

**Comment by KeaneYu** [comment]
+1 on it. Using version 1.58, the chart with forecast mark even became empty (as below). 
![image](https://user-images.githubusercontent.com/14102746/142985616-696d9aef-deef-4525-9444-fa094f85f9a1.png)

**Comment by LucasHocker** [comment]
![datagaps](https://user-images.githubusercontent.com/34926264/143269153-8a1ea843-bccc-4bf1-a8c8-c0e0dddd2bbd.png)
Please use the `Connect gaps` feature in Data Explorer.
