### ISSUE TITLE
USQLCOLOR not working with pie charts

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#111]
Pie chart for USQLCOLOR not working post refactor. Other visualizations appear fine...

![image](https://user-images.githubusercontent.com/21313331/136980782-b4f12bda-31b2-4e48-beb3-e14860e675d8.png)

**Comment by LucasHocker** [comment]
Refactored ugly else/if tree

**Comment by thistooksomedoing** [comment]
This does not appear to be working again at the moment
