### ISSUE TITLE
Add !PU(help) request

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#113]
Allow !PU(help):url= in a markdown tile. Create a button or icon in the top section of the dashboard. If the right hand corner is too busy, then maybe move it before/after the title on the left. Clicking on the button/icon takes you to help for the specific dashboard.

![image](https://user-images.githubusercontent.com/21313331/137952875-1f950691-d60b-4c8d-9e08-9943c985b0b5.png)

![image](https://user-images.githubusercontent.com/21313331/137952981-f5375447-1b78-4e5b-80af-16f91f7c0dd2.png)

**Comment by LucasHocker** [comment]
Added !PU(ellipsis). Pushed to GitHub, adding to ChromeStore 1.58.
