### ISSUE TITLE
HeatMap - Legend colors are not all unique

### ISSUE THREAD

**Issue by jshuff27** [dynatrace-oss/DynatraceDashboardPowerups#115]
For the heatmap to work it requires that each legend color exist and be unique.  In some cases, DT is assigning the same color to more than one object, even when only 5 categories are being returned.   Then if you have many categories DT also stops assigning legend colors.   I see those code attempts to handle this around line 5,441.  

As a result we get a heatmap with both the caught errors on the Y-Axis.

Not sure if there is a way to not be dependent on the legend colors. This will likely resolve both issues. 1 that duplicate colors will have no impact. 2 there will essentially be no limit to the number categories.

The next problem I foresee is when DT puts "30 more items" in the legend.

**Comment by TechShady** [comment]
So Apdex by application for both heatmaps, correct?

**Comment by TechShady** [comment]
I’ll send you a link to another workflow. It supports up to 28 apps. You select each app and then the next page has options for metric like Apdex and interval like 1 hour. 5 minutes. 1 day. Etc. Then the last page allows you to specify thresholds for each application.

**Comment by jshuff27** [comment]
So far so AMAZING.....i created a sample dashboard and will review it with the team.  I'm just constantly amazed at what you guys are doing here.  And so quickly.   Hopefully this all eventually makes it into DT native. Thanks so much for the solution.  I'll get back to you with what the team things of it.
