### ISSUE TITLE
Colorize plain text title cards/markdown 

### ISSUE THREAD

**Issue by brennanmuir** [dynatrace-oss/DynatraceDashboardPowerups#116]
Only way to do so is !PU(date) and escaping each character under fmt 

Example:
`!PU(date):res=now;fmt=\S\l\o\w\e\s\t_\B\r\o\w\s\e\r\s_\b\y_\C\o\u\n\t\r\y;color=red`

**Comment by LucasHocker** [comment]
Added !PU(color) to markdown and header tiles. It only support color=blue style syntax, no value based color changes. Pushed to GH, ChromeStore 1.58
