### ISSUE TITLE
Allow !PU(tilecss): to work in markdown tiles

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#117]
Would like to do something like this:

!PU(svg):icon=creditcard
!PU(tilecss):`border:3px green solid;border-radius: 15px;transform: rotateZ(45deg);`

The use case is to have an icon (maybe the help icon) and then use tilecss to move it to a different spot on the dashboard.

**Comment by LucasHocker** [comment]
Confirmed looking for TITLE_SELECTOR, MARKDOWN_SELECTOR. Need to do more testing.

**Comment by LucasHocker** [comment]
No bug. Markdown interprets backticks. To use backticks in markdown you need to escape them with a backslash
![Screen Shot 2021-11-08 at 12 09 52 PM](https://user-images.githubusercontent.com/34926264/140795293-5ac680e5-3b9b-40f3-aa4d-2edfa6a6d6b6.png)
.
