### ISSUE TITLE
!PU(table) sort not updating first column

### ISSUE THREAD

**Issue by jshuff27** [dynatrace-oss/DynatraceDashboardPowerups#118]
This might be related just to Data Explorer tables. 

I create a Data Explorer table then used the !PU(table). The table consists of just the host name and the CPU Usage %.   I created a table both without setting the sort value in Data Explorer and with setting the sort value in Data Explorer, and had the same result.     

The table displays in the dashboard just fine. Powerup re-renders the table.  I can click on the  CPU Usage % column header and it does successfully sort the CPU Usage % in ASC and DESC order but the first column, which is the Host Name remains where it is with no changes.   If I were to click on the Host Column (first column) i see the CPU Usage % re-order but again the Host Names don't move.

**Comment by LucasHocker** [comment]
Added handling for when cells are <a> instead of <span>, resolving unsorted column. Also found an issue with numeric sorting, which is also now fixed. Uploaded to GitHub, adding to ChromeStore version 1.58.
