### ISSUE TITLE
!PU fails to be applied

### ISSUE THREAD

**Issue by thistooksomedoing** [dynatrace-oss/DynatraceDashboardPowerups#119]
If the data explorer query underlying a !PU honeycomb or gauge on the dashboard returns 'no data', any !PU which appears after it in the JSON code will fail to be applied despite the query still working and returning data.

Image available if required, but will share directly due to info contained within.

**Comment by LucasHocker** [comment]
Reproduced for honeycomb, error handling added preventing crash. Unable to reproduce for gauge. Please open a new issue with reproduce details if gauge still has an issue.
