### ISSUE TITLE
!PU(vlookup) failing to pull character strings

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#121]
vlookup that pulls a character string fails. The result is 0.

![image](https://user-images.githubusercontent.com/21313331/138910576-b17545f1-4416-468f-a6d9-7c3335412db4.png)

**Comment by LucasHocker** [comment]
Unable to reproduc
![Screen Shot 2021-11-05 at 2 02 38 PM](https://user-images.githubusercontent.com/34926264/140564690-eae4dce0-0f6e-4004-a3e6-322424001cad.png)
e

**Comment by TechShady** [comment]
Fixed with new option for strings
