### ISSUE TITLE
Add colorization to the menu button if the tile has !PU(menu):

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#122]
The thought here is to make the buttons stand out if the tile has !PU(menu):. This way the user of the dashboard can easily tell if the tile has drilldown links associated with it. Maybe just add it as an option in the !PU(menu): syntax.

**Comment by LucasHocker** [comment]
Added .powerupMenuIcon css class. Pushed to GH, ChromeStore 1.58.
