### ISSUE TITLE
Need additional unit conversion (ones)

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#125]
If Explorer reports a value say 2.64 mil, The lowest unit I can convert that to is K. Or 2,640 k. I'd like to convert that to 2,640,000, or basically a "ones" unit conversion.

**Comment by LucasHocker** [comment]
Fixed bug which prevented you from using a blank unit, ie: 
!PU(vlookup):asdf;unit= <-- treats unit as "" which matches singles
!PU(vlookup):asdf <-- no unit, do not use units.

Fix pushed to GH, ChromeStore 1.58.
