### ISSUE TITLE
USQLCOLOR not working with pie charts

### ISSUE THREAD

**Issue by thistooksomedoing** [dynatrace-oss/DynatraceDashboardPowerups#127]
Same as this issue https://github.com/dynatrace-oss/DynatraceDashboardPowerups/issues/111

**Comment by LucasHocker** [comment]
![Screen Shot 2021-11-24 at 9 34 09 AM](https://user-images.githubusercontent.com/34926264/143268091-a0be0edc-577b-4f9e-affc-4a9f4b70e4fc.png)
I'm unable to reproduce your issue. Can you please share the syntax you're using?

**Comment by thistooksomedoing** [comment]
Sure, this is what I have set up:

![image](https://user-images.githubusercontent.com/91284658/143301616-3d00b57e-1b45-4fd6-bc31-1443fcc06d3f.png)

**Comment by thistooksomedoing** [comment]
But it still renders like this on a PU enabled dashboard:
![image](https://user-images.githubusercontent.com/91284658/143301946-b165a341-eed7-4221-8807-4fb0c2113e58.png)

**Comment by LucasHocker** [comment]
It looks like this isn't working because the values do not match. The powerup is looking for `satisfied` but the value is `satisfied, telus`. Please try removing ISP from the usql query and try again.

**Comment by thistooksomedoing** [comment]
ahh, good point. That's exactly what it was. My bad! Sorry.
