### ISSUE TITLE
Enhancements to PU table

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#131]
Allow a column (the primary column someting like usersessionid) to be linkable. Use the same syntax for homeycomb, so $name would be the primary column like usersessionid and then I can use that in a USQL query. Also allow thresholds for the columns and colorize the value or cell.

**Comment by TechShady** [comment]
Something like this...

![image](https://user-images.githubusercontent.com/21313331/145723536-a0d5769d-c810-4ae8-9f4d-5f8b026cb9ca.png)

**Comment by TechShady** [comment]
Something like this...

![image](https://user-images.githubusercontent.com/21313331/145723610-69111bd5-d343-4b1e-8734-26488ad85d70.png)

Original table...

![image](https://user-images.githubusercontent.com/21313331/145723632-abca964b-85f9-4738-a27e-e306b514a8a4.png)

**Comment by LucasHocker** [comment]
Added `url` parameter for drilldown. Pushed to GH, ChromeStore 1.59.
