### ISSUE TITLE
Need to escape app name when used as a drill in honeycomb PU

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#133]
I'm using the following honeycomb PU:

!PU(honeycomb):base=low;warn=20;crit=40;drill=/ui/user-sessions?filter=app:${app.name}&filter=browserFamily:$name&filter=errorType:Javascript%20error

If app.name has spaces in it, this breaks the drill. Can you make app.name URL friendly like it's done in other parts of the configurator swap?

Thanks,

**Comment by TechShady** [comment]
The drill link might also include filters for session properties that have spaces, like "New York" and those are populated at run time. Can the drill link be "cleaned up" with %20 for the spaces prior to launch? That would solve both the app filter and session property filters...

**Comment by LucasHocker** [comment]
Do you just need a new swap from Configurator that is uri encoded? If so, that’s an easy task. Originally I thought you were asking for something PowerUps based.

**Comment by TechShady** [comment]
I think it will be in both places. The $name is evaluated at PU run time so that would need to be something that PU escapes. The other filters are built with swaps, so that would be done in the configurator. So both.

**Comment by TechShady** [comment]
Just a configurator issue...
