### ISSUE TITLE
Sankey Chart exception

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#43]
highcharts-6.2.0-b44b69b.js:215 Uncaught TypeError: Cannot read property 'hoverPoint' of null
    at a.Pointer.onContainerClick (highcharts-6.2.0-b44b69b.js:215)
    at HTMLDivElement.b.onclick (highcharts-6.2.0-b44b69b.js:216)
onContainerClick @ highcharts-6.2.0-b44b69b.js:215
b.onclick @ highcharts-6.2.0-b44b69b.js:216

They error is likely related to larger useraction sets. I put an order by clause on the USQL query (order by userctioncount desc) to drive up longer flows for testing. The initial load works fine, but as I start to zoom in, I start getting the exception.

**Comment by LucasHocker** [comment]
set hard limit to 100 displayed user actions. Seems to prevent this error.
