### ISSUE TITLE
Icon Tooltip Doesn't Go Away After Clicking on Icon

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#44]
If you mouse over an icon with a tooltip, the tooltip displays fine. If you mouse away, the tooltip is removed. But if you click on the icon, the tooltip stays on the screen. The only way to remove it is to manually refresh the screen.

![image](https://user-images.githubusercontent.com/21313331/117494634-97896b80-af42-11eb-8cb7-c8d15c6ab315.png)

**Comment by LucasHocker** [comment]
Fixed in 1.48
