### ISSUE TITLE
export whole dashboard as pdf

### ISSUE THREAD

**Issue by Chooman66** [dynatrace-oss/DynatraceDashboardPowerups#46]
Not an issue, but can we have an option to export whole dashboard as pdf like we can tiles?

**Comment by LucasHocker** [comment]
Hi there! I'll certainly review what's possible. Just to understand the use case a bit more, why doesn't Print to PDF meet the need?

**Comment by Chooman66** [comment]
Hello Lucas,

This will be  a game changer for use as we need to send hourly PDFs to executives when DTE is in a storm with customer power outages. Print to PDF will work but want to do it for the whole dashboard, not just a tile.

Thanks,
Matt Klaus

From: Lucas Hocker ***@***.***>
Sent: Wednesday, May 12, 2021 1:48 PM
To: dynatrace-oss/DynatraceDashboardPowerups ***@***.***>
Cc: Matthew Klaus ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [dynatrace-oss/DynatraceDashboardPowerups] export whole dashboard as pdf (#46)


Hi there! I'll certainly review what's possible. Just to understand the use case a bit more, why doesn't Print to PDF meet the need?

-

**Comment by LucasHocker** [comment]
I'm continuing to look at this from a few angles. I found some libraries I could use to generate a PDF, but they had a ton of dependencies, so I would prefer to not go that route. Also investigating if there's a CSS solution that might work.
