### ISSUE TITLE
Request to create a Power Up for conditional icons

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#49]
Make icons conditional...if threshold is good, display the "good" icon. If threshold is bad, display the "bad" icon. Use the same logic that is used for Colorization.

Maybe something like this (would allow for 3 icons)...

!PU(svgconditional):icon=happy,fair,sad;link=val3;base=high;warn=90;crit=85

**Comment by LucasHocker** [comment]
added to 1.50
