### ISSUE TITLE
Sankey filter issue

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#50]
In the Sankey chart pop-up for actions displayed and actions filtered out, if you click on the number in parentheses after the user action and that user action has imbedded quotes, the filter applied to the chart is cutoff at the quote

![image](https://user-images.githubusercontent.com/21313331/120185327-0a9f9e00-c1e0-11eb-9ac7-44b61a90eb6f.png)

![image](https://user-images.githubusercontent.com/21313331/120186164-20619300-c1e1-11eb-89a5-47ced76e444a.png)

**Comment by LucasHocker** [comment]
refactored popup creation for proper escaping
