### ISSUE TITLE
Sankey Filtering

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#51]
Sankey chart shows 96 out of 103 user actions, but the actions currently filtered out doesn't list the 7 (103-96) actions.

![image](https://user-images.githubusercontent.com/21313331/120186961-302da700-c1e2-11eb-8cfc-1863d7811d43.png)

**Comment by LucasHocker** [comment]
refactored calculation for "actionsShown". Between X and Y should now match and correct actions shown in popup.

Note: this does not currently safely handle repeated action names across apps, e.g. "Loading page /" across 5 apps.
