### ISSUE TITLE
Column conversion for a table

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#53]
Need a power up that converts a table column to a different unit. If I select avg(duration) in USQL, the table will list the data in ms. Use case is to convert that to seconds.

Would be nice to support other conversions like MB to GB, but no request for that yet.

**Comment by LucasHocker** [comment]
<img width="1426" alt="Screen Shot 2021-06-10 at 3 32 15 PM" src="https://user-images.githubusercontent.com/34926264/121593214-46690d80-ca01-11eb-8783-d58e289c5e17.png">
This functionality already exists "in-product" for new explorer tables. Can a custom RUM metric + explorer be used for your use case?

**Comment by TechShady** [comment]
That should work.
