### ISSUE TITLE
mcompare not working with vlookup

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#55]
I have 3 tiles, 1 is a SVT and the other two are vlookup. I do a mcompare for the 3 tiles and only the SVT colorizes.

Here's the syntax for vlookup #1:

!PU(link):linka
!PU(vlookup):link=conversiondurationtable;val=payment/sign_in;col=1
!PU(mcompare):links=linka,linkb,linkc;low=green;high=red;other=yellow

Here's the syntax for vlookup #2:

!PU(link):linkb
!PU(vlookup):link=abandondurationtable;val=payment/sign_in;col=1
!PU(mcompare):links=linka,linkb,linkc;low=green;high=red;other=yellow

Here's the details on the SVT:

Duration !PU(mcompare):links=linka,linkb,linkc;low=green;high=red;other=yellow !PU(link):linkc

Abandon table:

Abandon Duration !PU(link):abandondurationtable

Conversion table:

Conversion Duration !PU(link):conversiondurationtable

![image](https://user-images.githubusercontent.com/21313331/121403117-9b852080-c928-11eb-929c-a42bd45f2f94.png)

**Comment by LucasHocker** [comment]
Refactored !PU(mcompare) to support vlookup tiles in addition to SVTs. Change pushed to GH, including in v1.51
