### ISSUE TITLE
mcompare not coloring values correctly

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#56]
![image](https://user-images.githubusercontent.com/21313331/121716642-4410bd00-caae-11eb-863c-e62baae5b31a.png)

The screen shot above is comparing the 3 values in each column. One should be green, one yellow and one red.

**Comment by LucasHocker** [comment]
New vlookup tile support for mcompare was incorrectly interpreting certain number strings as dates. Fix pushed to github, included in 1.51
