### ISSUE TITLE
Add color override for OOTB Honeycomb Tiles

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#57]
When viewing certain honeycomb tiles, like synthetics, the chart displays only green/red based on the success/failure of the synthetic monitor. If a monitor is disabled and it's last run was successful, the cell shows green. This request is to override that green color for disabled monitor (last run was good) or red color for disabled monitor (last run was bad) to grey. This would depend on the status of the monitor. The field is called status and I can filter the chart on that, but not sure if "status" is exposed where the powerup could just color those cells grey. Hopefully it is...

**Comment by LucasHocker** [comment]
this doesn't seem possible without making some sort of api call
