### ISSUE TITLE
Add honeycomb support for USQL tables

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#58]
Honeycomb power up works with USQL, but the cell coloring is greyed out. Allow support for coloring based on parameters. 

Example USQL query: select distinct browserMajorVersion, numberOfRageClicks FROM usersession where numberOfRageClicks>0 ORDER BY numberOfRageClicks DESC

Honeycomb result:
![image](https://user-images.githubusercontent.com/21313331/122410785-3b0e6880-cf52-11eb-988e-ac669371e3d0.png)

Allow parameters that provide coloring options. Like warn=2;crit=5. Then cells with 1 rage click in my example would be green. 2, 3 & 4 rage clicks would be yellow. 5 and over would be red.

**Comment by LucasHocker** [comment]
Pushed to Github and added to 1.51
<img width="352" alt="Screen Shot 2021-06-20 at 10 26 56 PM" src="https://user-images.githubusercontent.com/34926264/122704851-25cb5f80-d21a-11eb-9b2b-806270d7d3b8.png">
