### ISSUE TITLE
If you select only one forecast analysis (like Mean), the labels for the other analysis types show on the graph

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#60]
![image](https://user-images.githubusercontent.com/21313331/122974995-e3606a80-d360-11eb-8018-572bf429a41d.png)

The other forecast labels are not selectable...they just show up.

**Comment by LucasHocker** [comment]
Added option `leg=EMA`. Pushed to GitHub, added to ChromeStore 1.56.
