### ISSUE TITLE
vlookup causes error beacon and PU stops

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#65]
When running vlookup against a table with no data, the error beacon fires and PU stops processing. I used the notfound=0 parameter, but it didn't work. Works for nulls, but not "No Data"

![image](https://user-images.githubusercontent.com/21313331/124022235-8ac14b00-d9ba-11eb-8468-4770e7a3ff09.png)

![image](https://user-images.githubusercontent.com/21313331/124022330-a9274680-d9ba-11eb-8232-6a79edebf8b5.png)

**Comment by LucasHocker** [comment]
Fix added to 1.52

**Comment by TechShady** [comment]
Thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
