### ISSUE TITLE
Add unit capabilities to Math 

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#67]
So 17K becomes 17,000 and not 17.

**Comment by TechShady** [comment]
Can this be an option for vlookup as well? Add a unit parameter and then convert the result after vlookup before posting...

**Comment by LucasHocker** [comment]
Added `unit=` to PU(math) and PU(vlookup). Pushed to GitHub, added to ChromeStore version 1.55.
