### ISSUE TITLE
configure icons with Dynatrace Dashboard Powerups

### ISSUE THREAD

**Issue by elisaGaiti** [dynatrace-oss/DynatraceDashboardPowerups#69]
Hi,
i want to configure Icons icon=smiley-happy-1,smiley-ok-2,smiley-unhappy-2 depend on apdex level for user action of application.
How i can configure in a dashboard? where i put the configuration and how?
Thanks
Elisa Gaiti

**Comment by TechShady** [comment]
Create a markdown tile. Enter in something like this:

!PU(svg):icon=smiley-happy-1,smiley-ok-2,smiley-unhappy-2;link=apdexscore;base=high;warn=.90;crit=.80

Then create a single value tile custom chart (metric: Apdex (by user type) [web]). Make sure it's a single value. Add !PU(link):apdexscore to the title of the custom chart.

Make sure you markdown tile is a box so the image scales correctly.

Here's a sample json:

{
  "metadata": {
    "configurationVersions": [
      5
    ],
    "clusterVersion": "1.221.107.20210715-085203"
  },
  "id": "4f83cea4-9c23-4f7f-ab68-d05ecb71d27a",
  "dashboardMetadata": {
    "name": "New dashboard (Jul 22, 2021 16:28:01)",
    "shared": false,
    "owner": "john.kelly@dynatrace.com"
  },
  "tiles": [
    {
      "name": "",
      "tileType": "CUSTOM_CHARTING",
      "configured": true,
      "bounds": {
        "top": 0,
        "left": 0,
        "width": 304,
        "height": 304
      },
      "tileFilter": {},
      "filterConfig": {
        "type": "MIXED",
        "customName": "!PU(link):apdexscore",
        "defaultName": "Custom chart",
        "chartConfig": {
          "legendShown": true,
          "type": "SINGLE_VALUE",
          "series": [
            {
              "metric": "builtin:apps.web.apdex.userType",
              "aggregation": "AVG",
              "type": "LINE",
              "entityType": "APPLICATION",
              "dimensions": [],
              "sortAscending": false,
              "sortColumn": true,
              "aggregationRate": "TOTAL"
            }
          ],
          "resultMetadata": {}
        },
        "filtersPerEntityType": {}
      }
    },
    {
      "name": "Markdown",
      "tileType": "MARKDOWN",
      "configured": true,
      "bounds": {
        "top": 76,
        "left": 532,
        "width": 152,
        "height": 152
      },
      "tileFilter": {},
      "markdown": "!PU(svg):icon=smiley-happy-1,smiley-ok-2,smiley-unhappy-2;link=apdexscore;base=high;warn=.90;crit=.80"
    }
  ]
}
