### ISSUE TITLE
How to configure "grid" in dashboard

### ISSUE THREAD

**Issue by elisaGaiti** [dynatrace-oss/DynatraceDashboardPowerups#70]
Hi,
I want to use the grid lines to my dashboard.
I read in the documentation"https://github.com/dynatrace-oss/DynatraceDashboardPowerups#Grid" that i use this 
!PU(grid):hor=0,9,18;ver=0,9,18,27,35;color=#454646
But where i put this command in my Dashboard?
Thank you a lot
Elisa Gaiti

**Comment by TechShady** [comment]
Add a markdown tile to your dashboard and include something like this:

!PU(grid):hor=0,9,18;ver=0,9,18,27,35;color=#454646;margin=2

Move the tile to a spot below the page fold so it's not visible. This will "hide" it.

**Comment by TechShady** [comment]
I'll close this, but if you still need help, open another issue. Thanks.
