### ISSUE TITLE
Allow mcompare to work with links to math results

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#74]
Currently, mcompare works with SVT. Add support for links to math result for 2 SVT values.

Tile1:
!PU(vlookup):link=requests;row=1;col=5;size=44px
!PU(link):currentduration
!PU(math):exp=(a/b)*100;scope=a:currentduration,b:currentsessions;size=44px
!PU(mcompare):links=currentduration,previousduration;lt=green;gt=red;eq=yellow

Tile2:
!PU(vlookup):link=requests;row=2;col=5;size=44px
!PU(link):previousduration
!PU(math):exp=(a/b)*100;scope=a:previousduration,b:previoussessions;size=44px
!PU(mcompare):links=currentduration,previousduration;lt=red;gt=green;eq=yellow

**Comment by LucasHocker** [comment]
Fixed in 1.55
