### ISSUE TITLE
Request for a cumulative summary graph

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#77]
When graphing things like DDU consumption or revenue over time and you select SUM, then each data point in the graph is a sum for that time frame. This is good to show peaks and valleys. It would also be great to show cumulative growth, especially for things like DDU consumption. I know the total DDU purchased and I can set this as a threshold. If I could plot cumulative with forecasting, I can then project out to see if the customer will exceed the DDU purchased amount in the near future.

**Comment by TechShady** [comment]
Bumping this one to high...

**Comment by LucasHocker** [comment]
Having trouble visualizing what you're asking for... Either you want the data summed for an interval (ie a single point, depending on resolution) or you want it for the entire time range. Line/Bar provide the former table/toplist provide the latter.

**Sum for entire time range:**
<img width="1475" alt="Screen Shot 2021-09-29 at 4 50 34 PM" src="https://user-images.githubusercontent.com/34926264/135354697-79ccf2b4-85ba-4b49-af4b-6f0c301e20d9.png">

**Sums for intervals:**
<img width="1493" alt="Screen Shot 2021-09-29 at 5 03 33 PM" src="https://user-images.githubusercontent.com/34926264/135354920-c12d8f75-a2ff-4c79-9f0e-5a7d1d389685.png">
(DDUs summed per hour)

Are you asking to add plotlines on the y-axis to show a threshold?

**Comment by TechShady** [comment]
Here's a graph for sum of revenue
![image](https://user-images.githubusercontent.com/21313331/135355976-071545e9-be0a-45be-8596-4ee31ee18e15.png)

**Comment by TechShady** [comment]
I'd like to see this as a growth chart like this:
![image](https://user-images.githubusercontent.com/21313331/135356186-1c0274c7-f375-49a8-b72c-8b85e1b6af6f.png)

**Comment by LucasHocker** [comment]
Ahh that makes sense. This is doable with some data manipulation.

**Comment by TechShady** [comment]
So the power up would take each interval and keep rolling up the results.

16:20 $5,000
16:30 $4,000
16:40 $6,000

The plot lines would be $5,000 then $9,000 then $15,000 and so on

**Comment by TechShady** [comment]
And if we could add in a forecast and threshold PU as well, then we would really have something. So for things like DDU, I plot the growth and display the threshold...say 10M DDU. Then the forecast predicts that DDU will hit the purchased limit on Nov 15th. That's the end goal...

**Comment by TechShady** [comment]
Like this....

![image](https://user-images.githubusercontent.com/21313331/135357160-c995aba8-7451-4bfd-a021-6b3c1b99b457.png)

**Comment by LucasHocker** [comment]
Added `!PU(cumulative)`. Pushed to GitHub, added to ChromeStore 1.56.
