### ISSUE TITLE
Combine markdown expressions into a single tile + pull timeframe selector data

### ISSUE THREAD

**Issue by brennanmuir** [dynatrace-oss/DynatraceDashboardPowerups#80]
Currently it's not possible to have 2 dates in the same tile to represent a range
![image](https://user-images.githubusercontent.com/18177606/129804434-7947c7ec-63a3-42ba-ad84-346304023478.png)

In addition, if it could be possible to pull the time frame selector directly from the dashboards URL or HTML.

**Comment by TechShady** [comment]
Request to expand this request to allow multiple Math/vlookup functions that render into a single tile....

**Comment by LucasHocker** [comment]
Refactored date visualization to allow for mixing multiple dates plus text into a single tile. Additionally, added `$gtss` and `$gtse` to `res` for global time selector start and end. Example: `!PU(date):res=$gtss;fmt=MM/DD_HH:MM;color=orange - !PU(date):res=$gtse;fmt=MM/DD_HH:MM;color=orange`
<img width="331" alt="Screen Shot 2021-10-04 at 8 21 54 AM" src="https://user-images.githubusercontent.com/34926264/135858959-becc8e32-85ca-4310-9b11-487bdb6cd46c.png">

Pushed update to GitHub. Adding to ChromeStore 1.56.
