### ISSUE TITLE
Sankey tooltip for crash shows action count and not crash count

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#84]
![image](https://user-images.githubusercontent.com/21313331/131172176-2f42cb83-99fe-4968-bec0-867095e5f974.png)

**Comment by LucasHocker** [comment]
Unable to reproduce

<img width="1140" alt="Screen Shot 2021-09-05 at 4 07 29 PM" src="https://user-images.githubusercontent.com/34926264/132141503-d29b8599-f252-4908-b66c-80d61c450e52.png">
<img width="1202" alt="Screen Shot 2021-09-05 at 4 07 05 PM" src="https://user-images.githubusercontent.com/34926264/132141504-4993ced0-05e7-4de7-823b-9156b1e33d97.png">

**Comment by LucasHocker** [comment]
Was able to reproduce. Issue is caused by loop paths being counted multiple times for number of crashes.

Will add look-back mechanism to prevent duplicate counting.

**Comment by LucasHocker** [comment]
Added fix to prevent duplicate counting. Pushed to Github, will be added to Chromestore version 1.54
