### ISSUE TITLE
Sankey drill to sessions , crash groups, etc has the wrong URL encoed

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#85]
Link shows something like this: https://prod.dynatrace-managed.com/ui/mrum/MOBILE_APPLICATION-XXXXXXXX/analyze-crashes-noes/aXXXXXXX?gtf=-24h%20to%20now&gf=all

It should be this: https://prod.dynatrace-managed.com/e/XXXXXXXX/ui/mrum/MOBILE_APPLICATION-XXXXXXXX/analyze-crashes-noes/aXXXXXXX?gtf=-24h%20to%20now&gf=all

**Comment by LucasHocker** [comment]
Unable to reproduce

**Comment by TechShady** [comment]
Non issue. It's a mission control thing...
