### ISSUE TITLE
Need to display crash counts per action

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#87]
Can't do this in USQL. Maybe Custom Metric. The data is in the Sankey popup, so maybe add an export to that popup?

**Comment by LucasHocker** [comment]
Not completely sure whats needed here? Are you looking for a table with an aggregated count of the last action before a crash?

**Comment by TechShady** [comment]
Yes, table with aggregated count of the last action before crash,

**Comment by TechShady** [comment]
Use current Sankey for this analysis.
