### ISSUE TITLE
Add file name with filetype for PU table tile on download

### ISSUE THREAD

**Issue by imrankhan4z** [dynatrace-oss/DynatraceDashboardPowerups#88]
When it downloads, it just downloads with file name xlsx or csv but no type. Do you think it could be updated to download as something like filename.xlsx or filename.csv whichever user picks?
Thanks.

**Comment by LucasHocker** [comment]
Unable to reproduce. Please provide more details on how to reproduce issue.
<img width="1166" alt="Screen Shot 2021-09-07 at 8 18 46 AM" src="https://user-images.githubusercontent.com/34926264/132351947-d3cc7166-60f8-4e1e-9124-8ac07e9dc771.png">

**Comment by TechShady** [comment]
So, here's the issue. If the dashboard name has just "!PU(table):" and nothing else, it downloads without a filename. If you put in something like "Shady !PU(table):", it will download with the filename.extension.

![image](https://user-images.githubusercontent.com/21313331/132749310-89bc640a-b707-432e-941e-ef7feda7b1a4.png)

**Comment by imrankhan4z** [comment]
Hello, the one I was testing with had the title name after the !PU(table):. So it was something like !PU(table): User Action Count. Now of course you can rename it before downloading the file. But it becomes an issue for users who have auto download on from the browser. We will try adding the Title before !PU(table): and see if that resolves the issue.
Thanks.

**Comment by LucasHocker** [comment]
Unable to reproduce. Please reopen if needed.
