### ISSUE TITLE
vlookup with math doesn't refresh tile for auto refresh

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#89]
Original dashboard:

![image](https://user-images.githubusercontent.com/21313331/132383391-acde9617-51d6-4c3c-8c3b-a4b862b9f2cd.png)

After auto refresh:

![image](https://user-images.githubusercontent.com/21313331/132383489-a9781d49-38dd-47cf-b38b-2522998bf3d4.png)

![image](https://user-images.githubusercontent.com/21313331/132383590-8ccd9675-9d52-425e-bdd0-6f5a368c3749.png)

**Comment by TechShady** [comment]
Contents of tile that has NaN:

!PU(vlookup):link=table1;val=Ehub;col=1
!PU(link):app1nametable1
!PU(math):exp=(a/10);scope=a:app1nametable1;base=low;warn=5000;crit=6000;size=28px

**Comment by LucasHocker** [comment]
Added cleanupArtifacts() to remove artifacts from previous vlookup/math powerups. Seems to work.

Pushed to GH, will roll into 1.55 if there are no unintended consequences.
