### ISSUE TITLE
Math fails to store results if using both FULL & PRIO

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#95]
This works and the value is saved in lnkstep3abandonratecurrent

!PU(link):lnkstep3abandonratecurrent
!PU(math):exp=(a/b)*100;scope=a:lnkstep3abandonscurrent,b:lnkstep3current;base=low;warn=35;crit=50;prio=5

This doesn't work and the value saved is NULL

!PU(link):lnkstep3abandonratecurrent
!PU(math):exp=(a/b)*100;scope=a:lnkstep3abandonscurrent,b:lnkstep3current;base=low;warn=35;crit=50;full=false;prio=5

**Comment by TechShady** [comment]
https://guu84124.live.dynatrace.com/#dashboard;gtf=l_2_HOURS;id=bc8832dc-b12e-4251-833d-8f5f8993d87a;gf=all

Look at the upper left. The first column doesn't use FULL nd works fine. The second column uses FULL and the value stored in the link is NULL.

**Comment by TechShady** [comment]
A little more info. It's not a conflict when using both PRIO and FULL. It's FULL is broken now since PRIO was introduced. I added a third column to the dashboard above and removed all PRIOs. Left the FULL in place and it's broken.

**Comment by LucasHocker** [comment]
Artifact from changes required for PRIO. Corrected selector
