### ISSUE TITLE
Add the ability to specify colors with Honeycombs

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#97]

**Comment by LucasHocker** [comment]
What's the usecase here? I don't readily see the value in having blue, purple, etc honeycombs...

**Comment by TechShady** [comment]
The use case was specific to synthetics and having inactive synthetic test show up as grey in a honeycomb. I don't think the status is something that can be queried, so I'll close this one. This use case is better suited for API anyhow...
