### ISSUE TITLE
Add precision and scale to Math and Vlookup

### ISSUE THREAD

**Issue by TechShady** [dynatrace-oss/DynatraceDashboardPowerups#98]
Precision is the total number of digits and scale is the number of digits to the right of the decimal point in a number. For example, the number 123.45 has a precision of 5 and a scale of 2. Mainly need scale, but precision would be helpful as well.

**Comment by LucasHocker** [comment]
Added `dig=2` to math and vlookup, which sets the maximumFractionDigits. I think that meets the use case here. Pushed to GH, added to ChromeStore v1.56
